/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicPublicRouteImport } from './routes/(public)/_public'
import { Route as appProtectedRouteImport } from './routes/(app)/_protected'
import { Route as publicPublicIndexRouteImport } from './routes/(public)/_public/index'
import { Route as publicPublicSignupRouteImport } from './routes/(public)/_public/signup'
import { Route as publicPublicSigninRouteImport } from './routes/(public)/_public/signin'
import { Route as publicPublicForgotPasswordRouteImport } from './routes/(public)/_public/forgot-password'
import { Route as appProtectedProfileRouteImport } from './routes/(app)/_protected/profile'
import { Route as appProtectedExpensesRouteImport } from './routes/(app)/_protected/expenses'
import { Route as appProtectedDashboardRouteImport } from './routes/(app)/_protected/dashboard'
import { Route as appProtectedBudgetsRouteImport } from './routes/(app)/_protected/budgets'
import { Route as appProtectedAnalyticsRouteImport } from './routes/(app)/_protected/analytics'

const publicPublicRoute = publicPublicRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const appProtectedRoute = appProtectedRouteImport.update({
  id: '/(app)/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicSignupRoute = publicPublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicSigninRoute = publicPublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => publicPublicRoute,
} as any)
const publicPublicForgotPasswordRoute =
  publicPublicForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => publicPublicRoute,
  } as any)
const appProtectedProfileRoute = appProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appProtectedRoute,
} as any)
const appProtectedExpensesRoute = appProtectedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => appProtectedRoute,
} as any)
const appProtectedDashboardRoute = appProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appProtectedRoute,
} as any)
const appProtectedBudgetsRoute = appProtectedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => appProtectedRoute,
} as any)
const appProtectedAnalyticsRoute = appProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof appProtectedAnalyticsRoute
  '/budgets': typeof appProtectedBudgetsRoute
  '/dashboard': typeof appProtectedDashboardRoute
  '/expenses': typeof appProtectedExpensesRoute
  '/profile': typeof appProtectedProfileRoute
  '/forgot-password': typeof publicPublicForgotPasswordRoute
  '/signin': typeof publicPublicSigninRoute
  '/signup': typeof publicPublicSignupRoute
  '/': typeof publicPublicIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof appProtectedAnalyticsRoute
  '/budgets': typeof appProtectedBudgetsRoute
  '/dashboard': typeof appProtectedDashboardRoute
  '/expenses': typeof appProtectedExpensesRoute
  '/profile': typeof appProtectedProfileRoute
  '/forgot-password': typeof publicPublicForgotPasswordRoute
  '/signin': typeof publicPublicSigninRoute
  '/signup': typeof publicPublicSignupRoute
  '/': typeof publicPublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_protected': typeof appProtectedRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteWithChildren
  '/(app)/_protected/analytics': typeof appProtectedAnalyticsRoute
  '/(app)/_protected/budgets': typeof appProtectedBudgetsRoute
  '/(app)/_protected/dashboard': typeof appProtectedDashboardRoute
  '/(app)/_protected/expenses': typeof appProtectedExpensesRoute
  '/(app)/_protected/profile': typeof appProtectedProfileRoute
  '/(public)/_public/forgot-password': typeof publicPublicForgotPasswordRoute
  '/(public)/_public/signin': typeof publicPublicSigninRoute
  '/(public)/_public/signup': typeof publicPublicSignupRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/budgets'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/budgets'
    | '/dashboard'
    | '/expenses'
    | '/profile'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/'
  id:
    | '__root__'
    | '/(app)/_protected'
    | '/(public)/_public'
    | '/(app)/_protected/analytics'
    | '/(app)/_protected/budgets'
    | '/(app)/_protected/dashboard'
    | '/(app)/_protected/expenses'
    | '/(app)/_protected/profile'
    | '/(public)/_public/forgot-password'
    | '/(public)/_public/signin'
    | '/(public)/_public/signup'
    | '/(public)/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appProtectedRoute: typeof appProtectedRouteWithChildren
  publicPublicRoute: typeof publicPublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_public': {
      id: '/(public)/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_protected': {
      id: '/(app)/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/signup': {
      id: '/(public)/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicPublicSignupRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/signin': {
      id: '/(public)/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicPublicSigninRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(public)/_public/forgot-password': {
      id: '/(public)/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicPublicForgotPasswordRouteImport
      parentRoute: typeof publicPublicRoute
    }
    '/(app)/_protected/profile': {
      id: '/(app)/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProtectedProfileRouteImport
      parentRoute: typeof appProtectedRoute
    }
    '/(app)/_protected/expenses': {
      id: '/(app)/_protected/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof appProtectedExpensesRouteImport
      parentRoute: typeof appProtectedRoute
    }
    '/(app)/_protected/dashboard': {
      id: '/(app)/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appProtectedDashboardRouteImport
      parentRoute: typeof appProtectedRoute
    }
    '/(app)/_protected/budgets': {
      id: '/(app)/_protected/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof appProtectedBudgetsRouteImport
      parentRoute: typeof appProtectedRoute
    }
    '/(app)/_protected/analytics': {
      id: '/(app)/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appProtectedAnalyticsRouteImport
      parentRoute: typeof appProtectedRoute
    }
  }
}

interface appProtectedRouteChildren {
  appProtectedAnalyticsRoute: typeof appProtectedAnalyticsRoute
  appProtectedBudgetsRoute: typeof appProtectedBudgetsRoute
  appProtectedDashboardRoute: typeof appProtectedDashboardRoute
  appProtectedExpensesRoute: typeof appProtectedExpensesRoute
  appProtectedProfileRoute: typeof appProtectedProfileRoute
}

const appProtectedRouteChildren: appProtectedRouteChildren = {
  appProtectedAnalyticsRoute: appProtectedAnalyticsRoute,
  appProtectedBudgetsRoute: appProtectedBudgetsRoute,
  appProtectedDashboardRoute: appProtectedDashboardRoute,
  appProtectedExpensesRoute: appProtectedExpensesRoute,
  appProtectedProfileRoute: appProtectedProfileRoute,
}

const appProtectedRouteWithChildren = appProtectedRoute._addFileChildren(
  appProtectedRouteChildren,
)

interface publicPublicRouteChildren {
  publicPublicForgotPasswordRoute: typeof publicPublicForgotPasswordRoute
  publicPublicSigninRoute: typeof publicPublicSigninRoute
  publicPublicSignupRoute: typeof publicPublicSignupRoute
  publicPublicIndexRoute: typeof publicPublicIndexRoute
}

const publicPublicRouteChildren: publicPublicRouteChildren = {
  publicPublicForgotPasswordRoute: publicPublicForgotPasswordRoute,
  publicPublicSigninRoute: publicPublicSigninRoute,
  publicPublicSignupRoute: publicPublicSignupRoute,
  publicPublicIndexRoute: publicPublicIndexRoute,
}

const publicPublicRouteWithChildren = publicPublicRoute._addFileChildren(
  publicPublicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appProtectedRoute: appProtectedRouteWithChildren,
  publicPublicRoute: publicPublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
